/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'maperry' at '4/09/15 4:45 PM' with Gradle 2.4
 *
 * @author maperry, @date 4/09/15 4:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
